Creating plots and getting characteristics vignettes using Sphinx documentation
earthlab/streamstats pull request #332
Opened 2021-06-04 18:31 UTC by aefitts

Two vignettes containing information on creating plots and getting watershed characteristics using Sphinx documentation. @nkorinek

2021-06-08 18:05 UTC, nkorinek requested changes
Great job overall! Some minor notes on wording and specifics, but really well done in general! If you disagree with any of my notes just let me know and we can talk about it, happy to here your thoughts!

2021-06-08 18:05 UTC, nkorinek commented on examples/plot_get_characteristics.py
> +# hydrological unit code (HUC). StreamStats uses HUC to identify and delineate
Maybe link to some USGS docs on how they assign HUCs here?

2021-06-08 18:05 UTC, nkorinek commented on examples/plot_get_characteristics.py
> +# The function ``ws.characteristics`` will return the available basin
Since this is a function, would probably help to put parenthesis after it!

2021-06-08 18:07 UTC, nkorinek commented
@aefitts review above! Good job overall!

2021-06-10 21:08 UTC, nkorinek commented
@mbjoseph Hey! Ally and I worked on your docs and made a PR updating them to add sphinx gallery and some vignettes. If you want to review the PR, that would be awesome! But if you don't have time to be actively maintaining this repo no worries either, we would just need a way to merge it without you having to review it. Either way, let us know, thanks!

2021-06-11 03:32 UTC, mbjoseph commented
@nkorinek thanks for the heads up -- I'll leave it to you and the Earth Lab team to review etc. Great to see this come to fruition! :clap:

2021-06-14 20:29 UTC, merged